run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - misspell
    - unparam
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - revive

  disable:
    - exhaustruct
    - paralleltest      # Not always applicable

linters-settings:
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/newbpydev/bubblyui
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - tests/fixtures
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - dupl
        - goconst
