# TEMPORARY CONFIGURATION: Linting disabled during active development
# This configuration completely disables linting to allow development to proceed
# without interference during the implementation of the reactive state system (Phase 2)

version: "2"

run:
  go: '1.24'
  timeout: 5m
  skip-dirs:
    - tmp

# Disable all linters while in active development
linters:
  disable-all: true
  enable:
    # All linters are disabled until implementation is more complete

linters-settings:
  goimports:
    local-prefixes: github.com/newbpydev/bubblyui

issues:
  # Set max issues to 0 to effectively disable all linting checks
  max-issues-per-linter: 0
  max-same-issues: 0
