package router

// RouteChangedMsg is sent when navigation completes successfully.
//
// This message is generated by Push() and Replace() commands and should
// be handled in the application's Update() method to trigger re-renders
// or other route-dependent logic.
//
// Fields:
//   - To: The new current route
//   - From: The previous route (nil if no previous route)
//
// Example:
//
//	func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
//		switch msg := msg.(type) {
//		case router.RouteChangedMsg:
//			fmt.Printf("Navigated from %v to %s\n", msg.From, msg.To.Path)
//			// Update UI based on new route
//		}
//		return m, nil
//	}
type RouteChangedMsg struct {
	To   *Route // The new current route
	From *Route // The previous route (nil if first navigation)
}

// NavigationErrorMsg is sent when navigation fails.
//
// This message is generated when route matching fails, validation fails,
// or other navigation errors occur. Applications should handle this to
// display error messages or fallback routes.
//
// Fields:
//   - Error: The error that occurred
//   - From: The route we were navigating from (nil if no current route)
//   - To: The navigation target that failed
//
// Example:
//
//	func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
//		switch msg := msg.(type) {
//		case router.NavigationErrorMsg:
//			fmt.Printf("Navigation failed: %v\n", msg.Error)
//			// Show error message or navigate to 404 route
//		}
//		return m, nil
//	}
type NavigationErrorMsg struct {
	Error error             // The error that occurred
	From  *Route            // The route we were on (nil if no current route)
	To    *NavigationTarget // The target we tried to navigate to
}

// NavigationMsg is a marker interface for navigation messages.
//
// This interface is implemented by RouteChangedMsg and NavigationErrorMsg
// to allow type-safe handling of navigation results. It provides a common
// type for functions that can return either success or error messages.
//
// Usage:
//
//	func handleNavigation(msg NavigationMsg) {
//		switch msg := msg.(type) {
//		case RouteChangedMsg:
//			// Handle successful navigation
//		case NavigationErrorMsg:
//			// Handle navigation error
//		}
//	}
type NavigationMsg interface {
	isNavigationMsg()
}

// Implement NavigationMsg interface for type safety
func (RouteChangedMsg) isNavigationMsg()    {}
func (NavigationErrorMsg) isNavigationMsg() {}
